INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 1, 10, 'M', 10);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 1, 20, 'M', 20);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 1, 30, 'M', 30);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 1, 1, 'H', 80);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 1, -1, 'L', 100);

INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 2, 5, 'M', 20);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 2, 15, 'M', 40);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 2, 1, 'H', 100);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 2, 2, 'H', 160);
INSERT INTO PRICING VALUES (NEXT VALUE FOR pricing_id_seq, 2, -1, 'L', 200);

INSERT INTO LOT VALUES (NEXT VALUE FOR lot_id_seq, 1, 'Cids Garage', 'Hammerhead', 20);
INSERT INTO LOT VALUES (NEXT VALUE FOR lot_id_seq, 2, 'Cindys Garage', 'Transylvania', 5);

INSERT INTO TICKET VALUES (NEXT VALUE FOR ticket_id_seq, 100, '2018-08-08 20:08:08', '2018-08-08 21:10:08', 30, false);